fusionjs/fusion-plugin-react-router

README.md, docs/migrations/00009.md, package.json, src/__tests__/__browser__/notfound.js, src/__tests__/__browser__/redirect.js, src/__tests__/__browser__/route.js, src/__tests__/__browser__/status.js, src/__tests__/__node__/notfound.js, src/__tests__/__node__/redirect.js, src/__tests__/__node__/route.js, src/__tests__/__node__/status.js, src/__tests__/__node__/switch.js, src/__tests__/plugin.js, src/modules/BrowserRouter.js, src/modules/Route.js, src/modules/ServerRouter.js, src/plugin.js, yarn.lock
=> Update behavior for handling events and route data

package.json, src/__tests__/plugin.js, src/plugin.js
=> Remove downstream and upstream events

package.json, src/__tests__/__node__/status.js, src/plugin.js, yarn.lock
=> Handle non-ssr case for ROUTER_DATA element

package.json, src/__tests__/notfound.browser.js, src/__tests__/notfound.node.js, src/__tests__/redirect.browser.js, src/__tests__/redirect.node.js, src/__tests__/route.browser.js, src/__tests__/route.node.js, src/__tests__/status.browser.js, src/__tests__/status.node.js, src/__tests__/switch.browser.js, src/__tests__/switch.node.js, yarn.lock
Created with fusion-orchestrate.
=> Upgrade create-universal-package@^3.2.x

package.json, src/__tests__/plugin.js, src/modules/BrowserRouter.js, src/plugin.js, yarn.lock
=> Migrate to createPlugin api

src/__tests__/notfound.browser.js, src/__tests__/notfound.node.js, src/__tests__/plugin.js, src/__tests__/redirect.browser.js, src/__tests__/redirect.node.js, src/__tests__/route.browser.js, src/__tests__/route.node.js, src/__tests__/status.browser.js, src/__tests__/status.node.js, src/__tests__/switch.browser.js, src/__tests__/switch.node.js, src/browser.js, src/index.js, src/modules/BrowserRouter.js, src/modules/Redirect.js, src/modules/Route.js, src/modules/ServerRouter.js, src/modules/Status.js, src/plugin.js, src/server.js
Created with fusion-orchestrate.
=> Add short MIT license header to all source files

src/plugin.js
=> Handle non object event payloads

package.json, src/__tests__/plugin.js, src/browser.js, src/server.js, yarn.lock
* Greenkeep dependencies.
* Workaround rolllup issue with imports and exports.
* Provide mock body to fix status code checks.
Fixes #80
=> Fix release verification errors

src/__tests__/plugin.js, src/plugin.js
=> Fix handling of route prefix

src/__tests__/plugin.js
=> Remove body setter from router tests

README.md
Add documentation for routing events/metrics and `trackingId`.
=> Update documentation - events and trackingId

package.json
- Implement flow fixes for 0.85 ([#201](https://github.com/fusionjs/fusion-plugin-react-router/pull/201))
=> Release v1.4.2

package.json
- Rename and export ContextRouterType ([#210](https://github.com/fusionjs/fusion-plugin-react-router/pull/210))
- Improve static types ([#209](https://github.com/fusionjs/fusion-plugin-react-router/pull/209))
=> Release v1.5.0-2

package.json
- Upgrade flow-bin@latest and any packages raising Flow complaints ([#220](https://github.com/fusionjs/fusion-plugin-react-router/pull/220))
=> Release v1.5.1-0

package.json
- Fix typings of Route ([#217](https://github.com/fusionjs/fusion-plugin-react-router/pull/217))
=> Release v1.5.2-0

package.json
- Test memory router, ensure Route onRoute is not required ([#232](https://github.com/fusionjs/fusion-plugin-react-router/pull/232))
- Fix typings of Route ([#217](https://github.com/fusionjs/fusion-plugin-react-router/pull/217))
=> Release v1.5.2-1

package.json
- Fix destructuring bug in Status ([#231](https://github.com/fusionjs/fusion-plugin-react-router/pull/231))
- Test memory router, ensure Route onRoute is not required ([#232](https://github.com/fusionjs/fusion-plugin-react-router/pull/232))
- Fix typings of Route ([#217](https://github.com/fusionjs/fusion-plugin-react-router/pull/217))
=> Release v1.5.2-2

package.json
- Fix destructuring bug in Status ([#231](https://github.com/fusionjs/fusion-plugin-react-router/pull/231))
- Test memory router, ensure Route onRoute is not required ([#232](https://github.com/fusionjs/fusion-plugin-react-router/pull/232))
- Fix typings of Route ([#217](https://github.com/fusionjs/fusion-plugin-react-router/pull/217))
=> Release v1.5.2

src/plugin.js
This fixes the following error:
```
Warning: You cannot change <Router history>
```
=> Add preservation of browser history across HMR

package.json
- Add preservation of browser history across HMR ([#239](https://github.com/fusionjs/fusion-plugin-react-router/pull/239))
=> Release v1.5.3-alpha.1

package.json
- Add preservation of browser history across HMR ([#239](https://github.com/fusionjs/fusion-plugin-react-router/pull/239))
=> Release v1.5.3

src/modules/Status.js
Resolves https://github.com/fusionjs/fusion-plugin-react-router/issues/243
=> Fix rendering of multiple children in Status component

package.json
- Fix rendering of multiple children in Status component ([#244](https://github.com/fusionjs/fusion-plugin-react-router/pull/244))
=> Release v1.5.4-0

package.json
- Fix rendering of multiple children in Status component ([#244](https://github.com/fusionjs/fusion-plugin-react-router/pull/244))
=> Release v1.5.4
